###

# curl -X POST "http://localhost:8000/v1/chat/completions"
#-H "Authorization: Bearer sk-aaabbbcccdddeeefffggghhhiiijjjkkk"
#-H "Content-Type: application/json"
#-d '{
#    "model": "16",
#    "messages": [
#        {
#            "role": "user",
#            "content": "Hello"
#        },
#        {
#            "role": "assistant",
#            "content": "Hi, how can I help you?"
#        }
#    ]
#}'
POST http://localhost:6006/v1/chat/completions
Authorization: Bearer sk-aaabbbcccdddeeefffggghhhiiijjjkkk
Content-Type: application/json

{
  "model": "chatglm2",
  "messages": [
    {
      "role": "user",
      "content": "Hello"
    }
  ]
}

###

